name: 'RPM Build'
description: 'Build RPMs from spec file template.'
inputs:
  spec_template:
    description: 'Path to the spec file template'
    required: true
  version:
    description: 'Version for the RPM'
    required: true
  release:
    description: 'Release number for the RPM'
    required: true
  approot:
    description: 'Application root directory'
    required: true
  project:
    description: 'Project name'
    required: true
  deploy_dir:
    description: 'Deployment directory'
    required: true
  run_lint:
    description: 'Whether to run rpmlint on the generated spec file'
    required: false
    default: 'true'
  rpmmacros_template:
    description: 'Path to the .rpmmacros template file'
    required: false

runs:
  using: 'docker'
  image: 'Dockerfile'

outputs:
  rpm_path:
    description: 'Path to the built RPM file'
  rpm_name:
    description: 'Name of the built RPM file'
  rpm_dir_path:
    description: 'Path to RPMS directory'
  spec_file:
    description: 'Path to the generated spec file'
