name: 'RPM build with spec template'
description: 'Build RPMs from spec template with custom macros'
author: 'Mait Kaasik'

inputs:
  spec_template:
    description: 'Path to the spec template file'
    required: true
  version:
    description: 'RPM version'
    required: true
  release:
    description: 'RPM release number'
    required: true
  approot:
    description: 'Application root directory'
    required: true
  project:
    description: 'Project name'
    required: true
  deploy_dir:
    description: 'Deployment directory'
    required: true
  rpmmacros_template:
    description: 'Path to the .rpmmacros template file'
    required: true
  run_lint:
    description: 'Whether to run rpmlint'
    required: false
    default: 'true'
  project_exclude_paths:
    description: 'What folders should not be copied to build root'
    required: false
    default: '.git,.gitea,deploy,.gitignore,.idea'
  environment:
    description: 'What environment does app use'
    required: true

outputs:
  spec_file:
    description: 'Path to the generated spec file'
  rpm_path:
    description: 'Path to the built RPM file'
  rpm_name:
    description: 'Name of the built RPM file'
  rpm_dir_path:
    description: 'Path to the directory containing the built RPM'

runs:
  using: 'docker'
  image: 'Dockerfile'

branding:
  icon: 'package'
  color: 'yellow'
